spring.application.name=ResumeAnalyzer

# MySQL Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/resume_db
spring.datasource.username=root
spring.datasource.password=root

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Server Port
server.port=8080
openrouter.api.key=${OPENROUTER_API_KEY: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}