spring.application.name=ResumeAnalyzer

# PostgreSQL Configuration
spring.datasource.url=${DB_URL:jdbc:postgresql://dpg-d9d42hqhil2s73b9foig-a.oregon-postgres.render.com:5432/resume_db_7347}
spring.datasource.username=${DB_USERNAME:resume_db_7347_user}
spring.datasource.password=${DB_PASSWORD:1cnbtvou8DjYnCkNgUxeH0mweWuTclHg}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# CORS Configuration
cors.allowed.origins=${ALLOWED_ORIGINS:http://localhost:5173,https://ai-resume-analyzer-chi-silk.vercel.app}

# Server Port
server.port=8080
openrouter.api.key=${OPENROUTER_API_KEY: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}